version: "2.3"
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
  dynamodb-migration:
    image: node:alpine
    depends_on:
      - dynamodb
    volumes:
      - .:/opt/
    command: sh -c "cd /opt && npm install && node src/dynamo_schema.js"
  oauth-proxy:
    build:
      context: ./
      target: base
      dockerfile: ./Dockerfile
    depends_on:
      - dynamodb
    ports:
      - "7100:7100"
      - "9229:9229"
    environment:
      # The values here must match the values found in dynamo_schema.js.
      - AWS_ACCESS_KEY_ID=NONE
      - AWS_SECRET_ACCESS_KEY=NONE
      - AWS_DEFAULT_REGION=us-west-2
    volumes:
      - ./dev-config.json:/etc/oauth-proxy/config.json
    command: "node --inspect=0.0.0.0:9229 src/index.js --config /etc/oauth-proxy/config.json"
